# Site settings
title: Blair Nangle
description: "Blair Nangle's blog"
url: "https://blairnangle.com"

# Google Analytics
google_analytics: UA-124521773-1

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji
  - jekyll-gist

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Themes
remote_theme: chesterhow/tale

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
